### ISSUE TITLE
Convert dependencies to peer dependencies?

### ISSUE THREAD

**Issue by mario-d-s** [simplifiedcourses/ngx-signal-state#12]
Hi,

I want to throw in a quick congratulations first for the launch of this library. You're always posting brilliant stuff on simplified.courses - simply unmatched!

I had a quick look around and I immediately noticed all the Angular core libraries are specified as `dependencies` instead of `peerDependencies`. To my knowledge, this creates a pitfall because if your consumers don't use the exact same version of Angular, they'll end up shipping Angular **twice** to the browser (once as dependency of `ngx-signal-state` and once for their app). At the same time this locks consumers to one specific Angular version if they want to use `ngx-signal-state`. 

Oh and at the same time (the reason I noticed this): having actually 0 dependencies is a **big** selling point in my opinion! That definitely should shine out on the table you have there in the README 🙂 

I can write up a PR if you agree - or you can school me and say this is not really an issue and Angular handles this differently somehow :)

**Comment by simplifiedcourses** [comment]
Hi Mario!

Thanks a lot for reaching out and complimenting the articles! Much appreciated!!
Could it be that you are looking at the root package.json? 
This is the package.json that is shipped along with the package. 
`https://github.com/simplifiedcourses/ngx-signal-state/blob/master/projects/ngx-signal-state/package.json`

The peer dependencies look like this:

```json
"peerDependencies": {
    "@angular/core": ">=16.0.0",
    "@angular/common": ">=16.0.0",
    "rxjs": ">=6.0.0"
  },
```
Does that answer your question?

Cheers!

**Comment by mario-d-s** [comment]
@simplifiedcourses oh yes I was indeed looking at the root `package.json` - my bad!
You can (and should, imo) still advertise the 0 dependencies on the readme though!
