### ISSUE TITLE
Redux DevTools

### ISSUE THREAD

**Issue by mhosman** [simplifiedcourses/ngx-signal-state#14]
Hey! Great library!!! There’s a way to see the state of the app using Redux DevTools? Thanks!

**Comment by simplifiedcourses** [comment]
Hi! Thanks for reaching out! There aren't any actions so they can't be logged. I don't miss them though, If you want to listen to the state you can just log the state in an effect

```typescript
effect(() => {
  console.log(this.state())
})
```

Otherwise you can print it in the dom
```html
<pre>{{state()|json}}</pre>
```
