### ISSUE TITLE
connect() should act on each key independently

### ISSUE THREAD

**Issue by danielsharvey** [simplifiedcourses/ngx-signal-state#17]
The `connect()` method functions differently when compared to `ObservableState`. 

Specifically, for a call to connect, an update to any of the connected signals will re-call `patch()` for **ALL** of the keys (the effect is re-run).

I don't think this is the correct behaviour - at the very least it is inconsistent with `ObservableState` and `connectObservables()`.

I suggest that each key in the partial should be connected independently, and thus needs it own call to `effect()`.

Wdyt?

https://github.com/simplifiedcourses/ngx-signal-state/blob/f210dd14e1bfe9e704b0b867a5d63fa6320f7fad/projects/ngx-signal-state/src/lib/signal-state.ts#L111-L123

**Comment by simplifiedcourses** [comment]
You are absolutely right! Thanks for surfacing this

**Comment by simplifiedcourses** [comment]
https://github.com/simplifiedcourses/ngx-signal-state/pull/18 fixed here
