### ISSUE TITLE
Npm installation error

### ISSUE THREAD

**Issue by montoyafabian28** [simplifiedcourses/ngx-signal-state#9]
Hey! I want to try the library in a current angular 16 project, but I got this npm error on installation:
**npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.0.0" of package "@angular/common@>=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.**
Can you help me?

**Comment by simplifiedcourses** [comment]
Thank you for raising this:
I was not able to reproduce this but when googling I found:

- use yarn
- install with --legacy-peer-deps

Neither are a solution in my opinion so in this PR I dropped the carrot
https://github.com/simplifiedcourses/ngx-signal-state/pull/11
Can you try again with version 1.1.1?

Thanks!!

**Comment by montoyafabian28** [comment]
Working correctly, thank you!
